/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SingleResourceMeasurementAPIModel } from './singleResourceMeasurementAPIModel';


/**
 * Resource Analytics data response
 */
export interface AnalyticsResourceDataResponseDTOAPIModel { 
    /**
     * The average value of the included data
     */
    average?: number;
    /**
     * Array of ResourceDataDTO API Model
     */
    data?: Array<SingleResourceMeasurementAPIModel>;
    /**
     * The summary value of the included data
     */
    summary?: number;
}
