"use strict";
/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
exports.__esModule = true;
var PhenomenonUpdateDTO;
(function (PhenomenonUpdateDTO) {
    PhenomenonUpdateDTO.AggregationMethodEnum = {
        Min: 'min',
        Max: 'max',
        Average: 'average',
        Total: 'total'
    };
})(PhenomenonUpdateDTO = exports.PhenomenonUpdateDTO || (exports.PhenomenonUpdateDTO = {}));
