/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Data to be sent for processing
 */
export interface PublishDataDTOAPIModel {
    /**
     * The UUID of the Resource
     */
    resourceUuid: string;
    /**
     * The UNIX timestamp of the measurement
     */
    time: number;
    /**
     * The actual value of the measurement
     */
    value: number;
}
