/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PublishDataDTOAPIModel } from './publishDataDTOAPIModel';

/**
 * List of Data to be Published
 */
export interface PublishDataListDTOAPIModel { 
    /**
     * PublishDataDTO API Model
     */
    data: Array<PublishDataDTOAPIModel>;
}