/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QueryResourceDataCriteriaDTOAPIModel } from './queryResourceDataCriteriaDTOAPIModel';
/**
 * Object holding queries for latest Resource data
 */
export interface QueryLatestResourceDataDTOAPIModel {
    /**
     * QueryResourceDataCriteriaDTO API Model
     */
    queries: Array<QueryResourceDataCriteriaDTOAPIModel>;
}
