"use strict";
/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
exports.__esModule = true;
var QueryTimeRangeResourceDataCriteriaDTOAPIModel;
(function (QueryTimeRangeResourceDataCriteriaDTOAPIModel) {
    QueryTimeRangeResourceDataCriteriaDTOAPIModel.GranularityEnum = {
        _5min: '5min',
        Hour: 'hour',
        Day: 'day',
        Month: 'month'
    };
})(QueryTimeRangeResourceDataCriteriaDTOAPIModel = exports.QueryTimeRangeResourceDataCriteriaDTOAPIModel || (exports.QueryTimeRangeResourceDataCriteriaDTOAPIModel = {}));
