/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RegistryPairDTO } from './registryPairDTO';
export interface RegistryRecordDTO {
    pairs?: Array<RegistryPairDTO>;
    systemName?: string;
}
