"use strict";
/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var ResourceUpdateDTO;
(function (ResourceUpdateDTO) {
    ResourceUpdateDTO.TypeEnum = {
        Actuator: 'Actuator',
        Sensor: 'Sensor',
        Undefined: 'Undefined'
    };
})(ResourceUpdateDTO = exports.ResourceUpdateDTO || (exports.ResourceUpdateDTO = {}));
