/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Resource latest values Response API Model
 */
export interface ResourceLatestValuesResponseAPIModel { 
    /**
     * The last value the system received from the Resource
     */
    latest?: number;
    /**
     * The last 1 day aggregate computed for the Resource
     */
    latestDay?: number;
    /**
     * The last 5 minute aggregate computed for the Resource
     */
    latestMin5?: number;
    /**
     * The last 1 hour aggregate computed for the Resource
     */
    latestMin60?: number;
    /**
     * The last monthly aggregate computed for the Resource
     */
    latestMonth?: number;
    /**
     * The last time the system received a new measurement from the Resource
     */
    latestTime?: number;
    /**
     * The unit of measurement of a 'Sensor' Resource
     */
    uom?: string;
    /**
     * The Resource system name
     */
    uri?: string;
    /**
     * The UUID of the Resource
     */
    uuid?: string;
}
