/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The API Model describing a single Spark Works platform Resource Measurement API Model
 */
export interface SingleResourceMeasurementAPIModel { 
    /**
     * The actual value of the measurement
     */
    reading?: number;
    /**
     * The UNIX timestamp of the captured measurement
     */
    timestamp?: number;
}