/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The API Model holding Resource summary data of different granularity
 */
export interface TheResourceSummaryDataAPIModel { 
    /**
     * Average value of the aggregate arrays available above
     */
    average?: { [key: string]: number; };
    /**
     * The 42 latest 1-day aggregates computed by the system for the Resource
     */
    day?: Array<number>;
    /**
     * The 42 latest 1-day electricity cost values computed by the system for the Resource if enabled
     */
    dayCost?: Array<number>;
    /**
     * The Resource uniform resource identifier
     */
    keyName?: string;
    /**
     * The last value the system received from the Resource
     */
    latest?: number;
    /**
     * The value of a string value Resource
     */
    latestString?: string;
    /**
     * The last time the system received a new measurement from the Resource
     */
    latestTime?: number;
    /**
     * Maximum values of the aggregate arrays available above
     */
    max?: { [key: string]: number; };
    /**
     * Minimum values of the aggregate arrays available above
     */
    min?: { [key: string]: number; };
    /**
     * The 42 latest 5-minute aggregates computed by the system for the Resource
     */
    minutes5?: Array<number>;
    /**
     * The 42 latest 5-minute electricity cost values computed by the system for the Resource if enabled
     */
    minutes5cost?: Array<number>;
    /**
     * The 42 latest 1-hour aggregates computed by the system for the Resource
     */
    minutes60?: Array<number>;
    /**
     * The 42 latest 1-hour electricity cost values computed by the system for the Resource if enabled
     */
    minutes60cost?: Array<number>;
    /**
     * The 42 latest 1-month aggregates computed by the system for the Resource
     */
    month?: Array<number>;
    /**
     * The 42 latest 1-month electricity cost values computed by the system for the Resource if enabled
     */
    monthCost?: Array<number>;
}
