/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The API Participatory Sensing Resource Model
 */
export interface AParticipatorySensingResourceRequestAPIModel { 
    /**
     * The UUID of the Group of the Resource
     */
    groupUuid?: string;
    /**
     * The Resource name
     */
    name: string;
    /**
     * The name of a Spark Works platform property assigned to the Resource to describe the observed property
     */
    observes: string;
    /**
     * The Unit of Measurement of the Resource
     */
    uom: string;
}
