/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TimeZone } from './timeZone';


export interface FoodDiaryDTO { 
    carbohydrates?: number;
    createdTime?: number;
    createdTimeZone?: TimeZone;
    extra?: string;
    foodDbVersion?: number;
    id?: string;
    kilocalories?: number;
    localTime?: Date;
    mealType?: FoodDiaryDTO.MealTypeEnum;
    measureCode?: number;
    measureCount?: number;
    measureName?: string;
    measureUnit?: FoodDiaryDTO.MeasureUnitEnum;
    measureUnitCount?: number;
    order?: number;
    productCode?: number;
    productName?: string;
    user?: string;
}
export namespace FoodDiaryDTO {
    export type MealTypeEnum = 'BREAKFAST' | 'MAIN_MEAL' | 'OTHER_MEAL' | 'SNACK_DRINK';
    export const MealTypeEnum = {
        BREAKFAST: 'BREAKFAST' as MealTypeEnum,
        MAINMEAL: 'MAIN_MEAL' as MealTypeEnum,
        OTHERMEAL: 'OTHER_MEAL' as MealTypeEnum,
        SNACKDRINK: 'SNACK_DRINK' as MealTypeEnum
    };
    export type MeasureUnitEnum = 'GRAM' | 'ML';
    export const MeasureUnitEnum = {
        GRAM: 'GRAM' as MeasureUnitEnum,
        ML: 'ML' as MeasureUnitEnum
    };
}
