/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Food Diary Timerange criteria
 */
export interface FoodDiaryDataCriteriaDTO { 
    /**
     * The UUID of the food diary Resource
     */
    resourceUuid?: string;
    /**
     * The UNIX timestamp of the start date for filtering
     */
    from: number;
    /**
     * The UNIX timestamp of the end date for filtering
     */
    to: number;
}