/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * FoodDiary Data Timerange Query Criteria
 */
export interface FoodDiaryDataCriteriaDTOAPIModel { 
    /**
     * The UNIX timestamp of the start date for filtering
     */
    from: number;
    /**
     * The UUID of the food diary Resource
     */
    resourceUuid?: string;
    /**
     * The UNIX timestamp of the end date for filtering
     */
    to: number;
}
