/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Resource latest values Response API Model
 */
export interface LatestDTO { 
    /**
     * The UUID of the Resource
     */
    uuid?: string;
    /**
     * The Resource system name
     */
    uri?: string;
    /**
     * The unit of measurement of a 'Sensor' Resource
     */
    uom?: string;
    /**
     * The last time the system received a new measurement from the Resource
     */
    latestTime?: number;
    /**
     * The last value the system received from the Resource
     */
    latest?: number;
    /**
     * Refers to the aggregate of the 5 minutes concerning the latestTime
     */
    latestMin5?: number;
    /**
     * Refers to the aggregate of the hour concerning the latestTime
     */
    latestMin60?: number;
    /**
     * Refers to the aggregate of the day concerning the latestTime
     */
    latestDay?: number;
    /**
     * Refers to the aggregate of the month concerning the latestTime
     */
    latestMonth?: number;
}