/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Resource to be created and used for participatory sensing.
 */
export interface PSCreateResourceDTO { 
    /**
     * The Resource name
     */
    name: string;
    /**
     * The name of a Spark Works platform property assigned to the Resource to describe the observed property
     */
    observes: string;
    /**
     * The Unit of Measurement of the Resource
     */
    uom: string;
    /**
     * The UUID of the Group of the Resource
     */
    groupUuid?: string;
}