/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Resource Timerange Query Criteria
 */
export interface QueryTimeRangeResourceDataCriteriaDTO { 
    /**
     * The UUID of the Resource
     */
    resourceUuid?: string;
    /**
     * The Resource system name. The Resource UUID should be prefered. Left for compatibility with older applications.
     */
    resourceURI?: string;
    /**
     * The name of the target Unit of Measurement for the data to be returned. A valid Unit Conversion method between the two Units of Measurement should exist for the method to return valid data.
     */
    targetUom?: string;
    /**
     * The UNIX timestamp of the start date for filtering
     */
    from: number;
    /**
     * The UNIX timestamp of the end date for filtering
     */
    to: number;
    /**
     * The time granularity for the Resource data
     */
    granularity: QueryTimeRangeResourceDataCriteriaDTO.GranularityEnum;
    /**
     * The limit of returned results
     */
    resultLimit?: number;
}
export namespace QueryTimeRangeResourceDataCriteriaDTO {
    export type GranularityEnum = '5min' | 'hour' | 'day' | 'month' | '5min,hour,day,month';
    export const GranularityEnum = {
        _5min: '5min' as GranularityEnum,
        Hour: 'hour' as GranularityEnum,
        Day: 'day' as GranularityEnum,
        Month: 'month' as GranularityEnum,
        _5minhourdaymonth: '5min,hour,day,month' as GranularityEnum
    };
}