/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Data query criteria
 */
export interface QueryResourceDataCriteriaDTO { 
    /**
     * The UUID of the Resource
     */
    resourceUuid?: string;
    /**
     * The Resource system name. The Resource UUID should be prefered. Left for compatibility with older applications.
     */
    resourceURI?: string;
    /**
     * The name of the target Unit of Measurement for the data to be returned. A valid Unit Conversion method between the two Units of Measurement should exist for the method to return valid data.
     */
    targetUom?: string;
}