/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import {ResourceDataDTO} from "./resourceDataDTO";

/**
 * Raw Data query response
 */
export interface QueryRawDataTimeRangeResultDTO {
    /**
     * The UUID of the Resource
     */
    resourceUuid?: string;
    /**
     * The Resource's Phenomenon UUID
     */
    phenomenonUuid?: string;
    /**
     * The Resource's Unit UUID
     */
    unitUuid?: string;
    /**
     * The UNIX timestamp of the start date for filtering
     */
    from: number;
    /**
     * The UNIX timestamp of the end date for filtering
     */
    to: number;
    /**
     * The requested raw data
     */
    results?: Array<ResourceDataDTO>;
}
