/**
 * SparkWorks Core API
 * Management Service for the SparkWorks Processing Engine
 *
 * OpenAPI spec version: v2.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Resource Timerange Query Criteria
 */
export interface QueryTimeRangeResourceDataCriteriaDTOAPIModel { 
    /**
     * The UNIX timestamp of the start date for filtering
     */
    from: number;
    /**
     * The time granularity for the Resource data
     */
    granularity: QueryTimeRangeResourceDataCriteriaDTOAPIModel.GranularityEnum;
    /**
     * The Resource system name.
     */
    resourceURI?: string;
    /**
     * The UUID of the Resource
     */
    resourceUuid?: string;
    /**
     * The limit of returned results
     */
    resultLimit?: number;
    /**
     * The target Unit of Measurement
     */
    targetUom?: string;
    /**
     * The UNIX timestamp of the end date for filtering
     */
    to: number;
}
export namespace QueryTimeRangeResourceDataCriteriaDTOAPIModel {
    export type GranularityEnum = '5min' | 'hour' | 'day' | 'month';
    export const GranularityEnum = {
        _5min: '5min' as GranularityEnum,
        Hour: 'hour' as GranularityEnum,
        Day: 'day' as GranularityEnum,
        Month: 'month' as GranularityEnum
    };
}
