/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The API Model describing a single Spark Works platform Resource Measurement API Model
 */
export interface ResourceDataDTO { 
    /**
     * The UNIX timestamp of the Date when the Spark Works platform measurement was captured
     */
    timestamp?: number;
    /**
     * The actual value of the measurement
     */
    reading?: number;
}