/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * The Resource Extended Query
 */
export interface ResourceExtendedQueryDTO { 
    systemName?: string;
    uuid?: string;
    phenomenonUuid?: string;
    unitUuid?: string;
    phenomenonName?: string;
    unitName?: string;
    resourceType?: ResourceExtendedQueryDTO.ResourceTypeEnum;
    controls?: string;
}
export namespace ResourceExtendedQueryDTO {
    export type ResourceTypeEnum = 'Actuator' | 'Sensor' | 'Undefined';
    export const ResourceTypeEnum = {
        Actuator: 'Actuator' as ResourceTypeEnum,
        Sensor: 'Sensor' as ResourceTypeEnum,
        Undefined: 'Undefined' as ResourceTypeEnum
    };
}