/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResourceDTO { 
    createdBy?: string;
    createdDate?: Date;
    lastModifiedBy?: string;
    lastModifiedDate?: Date;
    uuid?: string;
    userFriendlyName: string;
    systemName: string;
    type: ResourceDTO.TypeEnum;
    controls?: string;
    phenomenonUuid?: string;
    unitUuid?: string;
    deleted?: boolean;
    groupUuid: string;
    gatewaySystemName?: string;
}
export namespace ResourceDTO {
    export type TypeEnum = 'Actuator' | 'Sensor' | 'Undefined';
    export const TypeEnum = {
        Actuator: 'Actuator' as TypeEnum,
        Sensor: 'Sensor' as TypeEnum,
        Undefined: 'Undefined' as TypeEnum
    };
}