/**
 * SparkWorks Core (CaRGO) API
 * Access Interface for the SparkWorks IoT Data Analytics Platform
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@sparkworks.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {SleepLevelsDTO} from "./sleepLevelsDTO";

export interface SleepDataDTO {
    logId?: string;
    type?: string;
    dateOfSleep?: string;
    startTime?: Date;
    endTime?: Date;
    duration?: number;
    efficiency?: number;
    minutesAfterWakeup?: number;
    minutesAsleep?: number;
    minutesAwake?: number;
    minutesToFallAsleep?: number;
    timeInBed?: number;
    infoCode?: number;
    mainSleep?: boolean;
    isMainSleep?: boolean;
    levels?: SleepLevelsDTO;
}
